extends:
  - stylelint-config-sass-guidelines
  - stylelint-config-prettier
plugins:
  - stylelint-selector-bem-pattern
  - stylelint-scss
  - stylelint-order
rules:
  #? start of stylelint-config-sass-guidelines
  # At-rule
  at-rule-no-vendor-prefix: true
  #function
  function-url-quotes: always
  # general
  max-nesting-depth: 3
  # Media Feature
  media-feature-name-no-vendor-prefix: true
  #number
  number-leading-zero: always
  # scss
  scss/at-function-pattern: ^rc-.+
  scss/at-import-no-partial-leading-underscore: true
  scss/at-mixin-pattern: ^rc-.+
  # (note for $-vars we use a leading underscore for "private" variables)
  scss/dollar-variable-pattern:
    - ^_?rc-.+
    - ignore: local
  scss/selector-no-redundant-nesting-selector: true
  # selector
  selector-class-pattern:
    - ^rc-.+
    - resolveNestedSelectors: true
  selector-max-compound-selectors: 4
  selector-no-vendor-prefix: true
  selector-no-qualifying-type: true
  # string
  string-quotes: double
  # value
  value-no-vendor-prefix: true
  #? end of stylelint-config-sass-guidelines
  #? start of stylelint-order
  order/order:
    - - type: at-rule
        hasBlock: false
      - custom-properties
      - declarations
    - unspecified: ignore
      disableFix: true
  # https://github.com/sasstools/sass-lint/blob/develop/lib/config/property-sort-orders/smacss.yml
  order/properties-order:
    - display
    - position
    - top
    - right
    - bottom
    - left

    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    - align-content
    - align-items
    - align-self
    - justify-content
    - order

    - box-sizing

    - width
    - min-width
    - max-width

    - height
    - min-height
    - max-height

    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left

    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left

    - float
    - clear

    - resize

    - columns
    - column-count
    - column-gap
    - column-fill
    - column-rule
    - column-span
    - column-width

    - grid-gap
    - grid-template-columns

    - animation
    - animation-name
    - animation-timing-function

    - transform
    - transform-box
    - transform-origin
    - transform-style

    - transition
    - transition-delay
    - transition-duration
    - transition-property
    - transition-timing-function

    # Border

    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width

    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style

    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-left-radius
    - border-bottom-right-radius

    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color

    - outline
    - outline-color
    - outline-offset
    - outline-style
    - outline-width

    # Background

    - background
    - background-attachment
    - background-clip
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-size

    - fill

    - opacity

    # Text

    - color

    - font
    - font-family
    - font-size
    - font-smoothing
    - font-style
    - font-variant
    - font-weight

    - letter-spacing
    - line-height
    - list-style

    - text-align
    - text-decoration
    - text-indent
    - text-overflow
    - text-rendering
    - text-shadow
    - text-transform
    - text-wrap

    - white-space
    - word-spacing

    # Cursor

    - cursor
    - pointer-events
    - user-select

    # Other

    - appearance
    - border-collapse
    - border-spacing
    - box-shadow
    - caption-side
    - content
    - empty-cells
    - overflow
    - overflow-x
    - overflow-y
    - quotes
    - speak
    - table-layout
    - vertical-align
    - visibility
    - will-change
    - z-index
  #? end of stylelint-order
  #? strat of stylelint-scss
  # @-else
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  # @-if
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after: always-intermediate
  # @-rule
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - at-root
        - content
        - each
        - else
        - error
        - for
        - forward
        - function
        - include
        - if
        - mixin
        - return
        - use
        - warn
  #? end of stylelint-scss
  #? start of selector-bem-pattern
  plugin/selector-bem-pattern:
    componentName: ^[a-z]+(?:-[a-z]+)*$
    # <namespace>-<block>__<element>*--<modifier>*[<attribute>]*
    componentSelectors: ^\.rc-{componentName}(?:__[a-z]+(?:-[a-z]+)*)*(?:--[a-z]+(?:-[a-z]+)*)*(?:\[.+\])*$
    ignoreSelectors:
      - ^fieldset
      - ^\[aria\-disabled=(?:.+)\]
      - ^img
  #? end of selector-bem-pattern
